version: "1.0.0"

name: My first cookbook recipe
description: |
  This recipe will create a template recipe.yml file in your working directory, and add COOKBOOK.md readme file.

files:
  - path: COOKBOOK.md
    strategy: skip-if-exists

  - path: recipe.yml
    strategy: skip-if-exists
