version: "1.0.0"

name: ESLint for Node
description: |
  This will install some stuff and scaffold react project.
files:
  - path: .eslintrc.js
    strategy: skip-if-exists
    destination: tmp/.eslintrc.js
  
  - path: tmp/package.json
    strategy: merge
    
  - path: .depcheckrc
    strategy: replace
    destination: sample/.depcheckrc
  
  - path: zz/skf.js
    strategy: skip-if-exists
    destination: tmp/zz/dsdas/dsa/dsaskf.js
    
  - path: .env
    strategy: replace
    destination: tmp/.env
    
tags: 
  - name: eslint
    description: Install eslint files
  

    
    